const Constants = {
  TRACK_STATUS_ENABLED: 1,
  TRACK_STATUS_DISABLED: 2,
  TRACK_STATUS_INVALID: 3,
  TRACK_STATUS_HISTORY: 4,

  SUBSCRIPTION_PLAN_ID_FREE: 1,
  SUBSCRIPTION_PLAN_ID_BASIC: 2,
  SUBSCRIPTION_PLAN_ID_PRO: 3,
  SUBSCRIPTION_PLAN_ID_PREMIUM: 4,
  SUBSCRIPTION_PLAN_ID_CUSTOM: 5,
};

export default Constants;
