const Constants = {
  PLAN_CALL_TO_ACTION_TYPE_NONE: 1,
  PLAN_CALL_TO_ACTION_TYPE_CHECKOUT: 2,
  PLAN_CALL_TO_ACTION_TYPE_UPGRADE: 3,

  TRACK_STATUS_ENABLED: 1,
  TRACK_STATUS_DISABLED: 2,
  TRACK_STATUS_INVALID: 3,
  TRACK_STATUS_DELETED: 4,
  TRACK_STATUS_FINISHED: 5,

  TRACK_PRICE_STATUS_DECREASED: 1,
  TRACK_PRICE_STATUS_INCREASED: 2,
  TRACK_PRICE_STATUS_STABLE: 3,

  SUBSCRIPTION_STRIPE_PRICE_ID_FREE: null,
  SUBSCRIPTION_STRIPE_PRICE_ID_BASIC_MONTHLY: "price_1QZs4QFdysMlodbwF0ypOl5l",
  SUBSCRIPTION_STRIPE_PRICE_ID_PRO_MONTHLY: "price_1QZs5XFdysMlodbwUYPcKKuB",
  SUBSCRIPTION_STRIPE_PRICE_ID_PREMIUM_MONTHLY: "price_1QZs5vFdysMlodbwplAZEkSR",
  SUBSCRIPTION_STRIPE_PRICE_ID_ENTREPRISE_MONTHLY: "price_1QZs77FdysMlodbwGNrTkE2F",
  SUBSCRIPTION_STRIPE_PRICE_ID_BUSINESS_MONTHLY: "price_1QZs7SFdysMlodbwyNB4sY2r",
  SUBSCRIPTION_STRIPE_PRICE_ID_ELITE_MONTHLY: "price_1QZs85FdysMlodbwm5gZmLLe",
  SUBSCRIPTION_STRIPE_PRICE_ID_ULTIMATE_MONTHLY: "price_1QZs8JFdysMlodbwIJahAsJG",
  SUBSCRIPTION_STRIPE_PRICE_ID_BASIC_ANNUALLY: "price_1QZsAmFdysMlodbwY26Sbf73",
  SUBSCRIPTION_STRIPE_PRICE_ID_PRO_ANNUALLY: "price_1QZsC9FdysMlodbwOcJJYlMS",
  SUBSCRIPTION_STRIPE_PRICE_ID_PREMIUM_ANNUALLY: "price_1QZsDIFdysMlodbwpDhhKRw3",
  SUBSCRIPTION_STRIPE_PRICE_ID_ENTREPRISE_ANNUALLY: "price_1QZsEQFdysMlodbwOppnibX9",
  SUBSCRIPTION_STRIPE_PRICE_ID_BUSINESS_ANNUALLY: "price_1QZsG7FdysMlodbwNi2fzDDD",
  SUBSCRIPTION_STRIPE_PRICE_ID_ELITE_ANNUALLY: "price_1QZsIWFdysMlodbwlE8UItjr",
  SUBSCRIPTION_STRIPE_PRICE_ID_ULTIMATE_ANNUALLY: "price_1QZsJHFdysMlodbwrXxoQGWl",

  SUBSCRIPTION_BILLING_PERIOD_MONTHLY: 1,
  SUBSCRIPTION_BILLING_PERIOD_ANNUALLY: 2,
  SUBSCRIPTION_BILLING_PERIOD_FOREVER: 3,

  TRACKLIST_TAB_IN_PROGRESS: "in-progress",
  TRACKLIST_TAB_WISHLIST: "wishlist",
  TRACKLIST_TAB_INVALID: "invalid",
  TRACKLIST_TAB_FINISHED: "finished",

  SETTINGS_TAB_NOTIFICATIONS: "notifications",
  SETTINGS_TAB_ACCOUNT: "account",
  SETTINGS_TAB_SUBSCRIPTION: "subscription",

  DASHBOARD_TAB_REVENUE_METRICS: "revenue-metrics",
  DASHBOARD_TAB_USER_METRICS: "user-metrics",
  DASHBOARD_TAB_TRACK_METRICS: "track-metrics",

  URL_PARAMS_TO_SAVE: ["referrerCode"],
};

export default Constants;
